### ISSUE TITLE
failed to build image

### ISSUE THREAD

**Issue by fuchs0329** [mendix/docker-mendix-buildpack#100]
Hello,

could someone help me to check my problem? I tried to build mendix image. it works by using sample app.

but when i tried to build my own app. below error occurred:  a error while compiling java action. details please see below.

   __  __      ____        _ _     _
  |  \/  |    |  _ \      (_) |   | |
  | \  / |_  _| |_) |_   _ _| | __| |
  | |\/| \ \/ /  _ <| | | | | |/ _` |
  | |  | |>  <| |_) | |_| | | | (_| |
  |_|  |_/_/\_\____/ \__,_|_|_|\__,_|

   v8.9.0.5487

Starting build for Mendix Project file: /opt/mendix/build/Vehicle Management App.mpr
Using the following options:
 * Build target: Package
 * Deployment package file: /tmp/model.mda
Reading project file...
Building project...
Executing step 'Synchronize with file system'
 * Synchronizing with file system...
Executing step 'Initialize'
 * Preparing deployment...
Executing step 'Check prerequisites'
 * Checking for errors...
Executing step 'Clean deployment directory'
 * Cleaning deployment directory...
 * Cleaning web deployment directory...
Executing step 'Prepare deployment'
 * Writing files...
Executing step 'Build deployment structure'
 * Compiling Java...
ERROR: An error occurred while compiling Java actions
Buildfile: /opt/mendix/build/deployment/build_core.xml

compile:
    [javac] Compiling 55 source files to /opt/mendix/build/deployment/run/bin
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:392: error: cannot find symbol
    [javac]     public final vechiclemodule.proxies.ENU_Reservestatus getReservestatus()
    [javac]                                        ^
    [javac]   symbol:   class ENU_Reservestatus
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:401: error: cannot find symbol
    [javac]     public final vechiclemodule.proxies.ENU_Reservestatus getReservestatus(com.mendix.systemwideinterfaces.core.IContext context)
    [javac]                                        ^
    [javac]   symbol:   class ENU_Reservestatus
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:414: error: cannot find symbol
    [javac]     public final void setReservestatus(vechiclemodule.proxies.ENU_Reservestatus reservestatus)
    [javac]                                                              ^
    [javac]   symbol:   class ENU_Reservestatus
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:424: error: cannot find symbol
    [javac]     public final void setReservestatus(com.mendix.systemwideinterfaces.core.IContext context, vechiclemodule.proxies.ENU_Reservestatus reservestatus)
    [javac]                                                                                                                     ^
    [javac]   symbol:   class ENU_Reservestatus
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:436: error: cannot find symbol
    [javac]     public final vechiclemodule.proxies.ENU_ReserveStatusRequestorView getStatusInRequestorView()
    [javac]                                        ^
    [javac]   symbol:   class ENU_ReserveStatusRequestorView
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:445: error: cannot find symbol
    [javac]     public final vechiclemodule.proxies.ENU_ReserveStatusRequestorView getStatusInRequestorView(com.mendix.systemwideinterfaces.core.IContext context)
    [javac]                                        ^
    [javac]   symbol:   class ENU_ReserveStatusRequestorView
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:458: error: cannot find symbol
    [javac]     public final void setStatusInRequestorView(vechiclemodule.proxies.ENU_ReserveStatusRequestorView statusinrequestorview)
    [javac]                                                                      ^
    [javac]   symbol:   class ENU_ReserveStatusRequestorView
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:468: error: cannot find symbol
    [javac]     public final void setStatusInRequestorView(com.mendix.systemwideinterfaces.core.IContext context, vechiclemodule.proxies.ENU_ReserveStatusRequestorView statusinrequestorview)
    [javac]                                                                                                                             ^
    [javac]   symbol:   class ENU_ReserveStatusRequestorView
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:407: error: cannot find symbol
    [javac]             return vechiclemodule.proxies.ENU_Reservestatus.valueOf((java.lang.String) obj);
    [javac]                                          ^
    [javac]   symbol:   class ENU_Reservestatus
    [javac]   location: package vechiclemodule.proxies
    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:451: error: cannot find symbol
    [javac]             return vechiclemodule.proxies.ENU_ReserveStatusRequestorView.valueOf((java.lang.String) obj);
    [javac]                                          ^
    [javac]   symbol:   class ENU_ReserveStatusRequestorView
    [javac]   location: package vechiclemodule.proxies
    [javac] 10 errors

BUILD FAILED
/opt/mendix/build/deployment/build_core.xml:29: Compile failed; see the compiler error output for details.

Total time: 3 seconds

Writing list of project errors...
 * Project errors written to file '/tmp/builderrors.json'
BUILD FAILED
ERROR: MxBuild returned errors: {"errors": [{"message": "An error occurred while compiling Java actions", "details": "Buildfile: /opt/mendix/build/deployment/build_core.xml\n\ncompile:\n    [javac] Compiling 55 source files to /opt/mendix/build/deployment/run/bin\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:392: error: cannot find symbol\n    [javac] \tpublic final vechiclemodule.proxies.ENU_Reservestatus getReservestatus()\n    [javac] \t                                   ^\n    [javac]   symbol:   class ENU_Reservestatus\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:401: error: cannot find symbol\n    [javac] \tpublic final vechiclemodule.proxies.ENU_Reservestatus getReservestatus(com.mendix.systemwideinterfaces.core.IContext context)\n    [javac] \t                                   ^\n    [javac]   symbol:   class ENU_Reservestatus\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:414: error: cannot find symbol\n    [javac] \tpublic final void setReservestatus(vechiclemodule.proxies.ENU_Reservestatus reservestatus)\n    [javac] \t                                                         ^\n    [javac]   symbol:   class ENU_Reservestatus\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:424: error: cannot find symbol\n    [javac] \tpublic final void setReservestatus(com.mendix.systemwideinterfaces.core.IContext context, vechiclemodule.proxies.ENU_Reservestatus reservestatus)\n    [javac] \t                                                                                                                ^\n    [javac]   symbol:   class ENU_Reservestatus\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:436: error: cannot find symbol\n    [javac] \tpublic final vechiclemodule.proxies.ENU_ReserveStatusRequestorView getStatusInRequestorView()\n    [javac] \t                                   ^\n    [javac]   symbol:   class ENU_ReserveStatusRequestorView\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:445: error: cannot find symbol\n    [javac] \tpublic final vechiclemodule.proxies.ENU_ReserveStatusRequestorView getStatusInRequestorView(com.mendix.systemwideinterfaces.core.IContext context)\n    [javac] \t                                   ^\n    [javac]   symbol:   class ENU_ReserveStatusRequestorView\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:458: error: cannot find symbol\n    [javac] \tpublic final void setStatusInRequestorView(vechiclemodule.proxies.ENU_ReserveStatusRequestorView statusinrequestorview)\n    [javac] \t                                                                 ^\n    [javac]   symbol:   class ENU_ReserveStatusRequestorView\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:468: error: cannot find symbol\n    [javac] \tpublic final void setStatusInRequestorView(com.mendix.systemwideinterfaces.core.IContext context, vechiclemodule.proxies.ENU_ReserveStatusRequestorView statusinrequestorview)\n    [javac] \t                                                                                                                        ^\n    [javac]   symbol:   class ENU_ReserveStatusRequestorView\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:407: error: cannot find symbol\n    [javac] \t\treturn vechiclemodule.proxies.ENU_Reservestatus.valueOf((java.lang.String) obj);\n    [javac] \t\t                             ^\n    [javac]   symbol:   class ENU_Reservestatus\n    [javac]   location: package vechiclemodule.proxies\n    [javac] /opt/mendix/build/javasource/reconstructure/proxies/ReserveRecord.java:451: error: cannot find symbol\n    [javac] \t\treturn vechiclemodule.proxies.ENU_ReserveStatusRequestorView.valueOf((java.lang.String) obj);\n    [javac] \t\t                             ^\n    [javac]   symbol:   class ENU_ReserveStatusRequestorView\n    [javac]   location: package vechiclemodule.proxies\n    [javac] 10 errors\n\nBUILD FAILED\n/opt/mendix/build/deployment/build_core.xml:29: Compile failed; see the compiler error output for details.\n\nTotal time: 3 seconds\n\n\n"}], "problems": []}
WARNING: No build status callback url set, so not going to submit the status
ERROR: Command '['/tmp/opt/mono-5.20.1.27/bin/mono', '--config', '/tmp/opt/mono-5.20.1.27/etc/mono/config', '/opt/mendix/build/.local/mxbuild/modeler/mxbuild.exe', '--target=package', '--output=/tmp/model.mda', '--java-home=/opt/mendix/build/.local/usr/lib/jvm/AdoptOpenJDK-jdk-11.0.8-AdoptOpenJDK-x64', '--java-exe-path=/opt/mendix/build/.local/usr/lib/jvm/AdoptOpenJDK-jdk-11.0.8-AdoptOpenJDK-x64/bin/java', '--write-errors=/tmp/builderrors.json', '/opt/mendix/build/Vehicle Management App.mpr']' returned non-zero exit status 3.
Traceback (most recent call last):
  File "./compilation", line 66, in <module>
    exit_code = call_buildpack_compilation()
  File "./compilation", line 37, in call_buildpack_compilation
    return subprocess.check_call(["/opt/mendix/buildpack/buildpack/compile.py", BUILD_PATH, CACHE_PATH])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/mendix/buildpack/buildpack/compile.py', '/opt/mendix/build', '/tmp/buildcache']' returned non-zero exit status 1.
The command '/bin/sh -c mkdir -p /tmp/buildcache /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/compile.py &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chgrp -R 0 /opt/mendix /var/mendix &&    chmod -R g=u /opt/mendix /var/mendix' returned a non-zero code: 1
make: *** [build-image] Error 1

I uploaded my application to the Github below:
https://github.com/fuchs0329/mendix.git

**Comment by cstevandy** [comment]
you have a compilation error, if you open the mpr from mendix studio pro, you will also get the same things. Probably you missed some dependency when you exported the package.

**Comment by fuchs0329** [comment]
> you have a compilation error, if you open the mpr from mendix studio pro, you will also get the same things. Probably you missed some dependency when you exported the package.

hi Christian, 

i exported my project again, then it works.
thanks a lot for your help

have a nice day
