### ISSUE TITLE
SSL Setup in nginx

### ISSUE THREAD

**Issue by scchengaiah** [mendix/docker-mendix-buildpack#101]
Dear All,

Can someone help me out on how to setup SSL configuration for the app.

Currently, I've been using docker mendix buildpack for containerizing my application.

I could able to access via port 8080 on http, but I am unable to find any documentation with respect to nginx ssl configuration to expose port 443, setup self signed certificates and access the app via https.

Thank you.

Regards,
Chengaiah.

**Comment by MXClyde** [comment]
In short: SSL termination is not part of the scope of the buildpack. You have to place a reverse proxy in front of Mendix to handle SSL termination.

**Comment by scchengaiah** [comment]
Thanks for the response.
I was thinking like we already have a reverse proxy(nginx) in front of mendix. 
Hope there could be a way to configure the existing proxy instead of having an additional one.
Do you think that this feature to handle SSL connections adds more options to the buildpack.

**Comment by xiwenc** [comment]
As @MXClyde pointed out, the buildpack's purpose is to package a Mendix app into a docker image. With least possible cruft.

If you want SSL termination, either build it as a side car or use external load balancer. Containers are cheap, having another container with nginx is not going to change much. Depending on your case, you might be able to re-use this SSL termination reverse proxy for other backends/apps also.

**Comment by scchengaiah** [comment]
@xiwenc 
Thanks for the response I shall validate for the alternatives as suggested.

**Comment by macrel** [comment]
I know this thread is closed, but we have always used docker and added SSL termination by modifying the docker image (overwriting the nginx.conf file). 

We are using container optimized OS in the Google Cloud. It works fine, but now we want to use the docker buildpack without modifications. I can deploy and go to myip:8080 and see the Mendix app. However, I want to add a reverse proxy or load balancer with SSL termination in front of this which forwards to port 8080 in my VM. 

Any ideas on how to actually do this in the Google Cloud? How do I add an extra nginx container around the docker buildpack? I tried using the load balancer features in the GOogle Cloud but it's giving me a hard time with errors like "TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"

**Comment by scchengaiah** [comment]
The below docker compose contains app, database and nginx component that acts as reverse proxy. However, I have used custom ports for SSL.

`
version: "2.4"
services:
    app:
        container_name: mendixapp
        image: mendixapp:v1.0.0
        environment:
            ADMIN_PASSWORD: Admin@123
            DATABASE_ENDPOINT: "postgres://mendix:32VPZT756hKWqjBTB3kY@connectivitydb:5432/mendix"
        restart: always
        volumes:
            - app-data:/opt/mendix/build/data
        links:
            - connectivitydb
        networks:
            - proxy-redirect

    connectivitydb:
        container_name: connectivity-db
        image: postgres:12
        environment:
            - POSTGRES_USER=mendix
            - POSTGRES_PASSWORD=32VPZT756hKWqjBTB3kY
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - proxy-redirect
    nginx:
        container_name: connectivity-nginx
        image: nginx:alpine
        ports:
            - 38088:80
            - 38089:443
        networks:
            - proxy-redirect
        links:
            - app
        volumes:
            - /home/user/connectivity/nginx/conf.d:/etc/nginx/conf.d
            - /home/user/connectivity/nginx/certs:/etc/ssl/nginx
        mem_limit: 250m
        mem_reservation: 200m

# Internal named volumes definition.
volumes:
    app-data:
        name: app-data
    postgres-data:
        name: postgres-data

networks:
    proxy-redirect:
        external:
            name: proxy-redirect
        driver: bridge
`
We have configuration and certs mounted from host device.

**Comment by macrel** [comment]
Never mind, I just got it working.

I run the clean docker image with no changes on a Google Cloud VM. So it runs on port 8080. Then I have a load balancer with an HTTPS frontend and my SSL cert. The backend communicates over HTTP with the VM so it maps port 443 to 8080. 

It's actually a rather easy solution, although it took me 2 days to get it working. There is almost no documentation on these matters. 

My only concert right now is someone could still access my app over IP:8080 over the HTTP protocol isntead of HTTPS. But I guess that's somethine for the firewall. 

Do you think this solution is solid and safe or any downsides to this solution?

**Comment by scchengaiah** [comment]
I think the port 8080 is the container port. You can remove it from your port mapping and check if it is still accessible. Between, I don't have concrete experience in google cloud. You can check if this makes sense from that context.

**Comment by macrel** [comment]
@xiwenc :
Ah thanks, that makes sense (the private network thing). With deny all except load balancer rule you mean a firewall rule?

**Comment by xiwenc** [comment]
Yes indeed firewall or network security groups. Forgot what it's called in GCP.

**Comment by macrel** [comment]
Thanks! This will help me going for sure.
