### ISSUE TITLE
default user name ?  

### ISSUE THREAD

**Issue by iXieYi** [mendix/docker-mendix-buildpack#113]
![image](https://user-images.githubusercontent.com/21982108/109937651-19260880-7d0a-11eb-9d87-0c9bbcb16ea9.png)
![image](https://user-images.githubusercontent.com/21982108/109937025-82594c00-7d09-11eb-93e0-b853fdd9160d.png)
localhost:8080/login.html  
default user name ?  
![image](https://user-images.githubusercontent.com/21982108/109937596-09a6bf80-7d0a-11eb-91c9-2e07ccb72706.png)

**Comment by cstevandy** [comment]
The standard default admin username is MxAdmin. https://docs.mendix.com/refguide/administrator#user-name
