### ISSUE TITLE
run image fail 

### ISSUE THREAD

**Issue by iXieYi** [mendix/docker-mendix-buildpack#117]
![image](https://user-images.githubusercontent.com/21982108/112111559-50902280-8bef-11eb-9317-6b3e9042b238.png)
ERROR: Unable to fixup permissions of directory 'model' with mode 700: [Errno 1] Operation not permitted: '/opt/mendix/build/model', Ignoring.

ERROR: Unable to fixup permissions of directory 'web' with mode 755: [Errno 1] Operation not permitted: '/opt/mendix/build/web', Ignoring.

ERROR: Unable to fixup permissions of directory 'data' with mode 700: [Errno 1] Operation not permitted: '/opt/mendix/build/data', Ignoring.

What should I do？

**Comment by cstevandy** [comment]
Have you tried to set security settings to production?
![image](https://user-images.githubusercontent.com/5585679/112129788-0e071f80-8bc8-11eb-9798-9bf81b328656.png)

**Comment by iXieYi** [comment]
I set security settings to production,but now unable to make build image  😭
![Snip20210324_21](https://user-images.githubusercontent.com/21982108/112290585-5b6bb580-8cca-11eb-8721-05b77170311f.png)


> Have you tried to set security settings to production in your mendix app?
> ![image](https://user-images.githubusercontent.com/5585679/112129788-0e071f80-8bc8-11eb-9798-9bf81b328656.png)

**Comment by MXClyde** [comment]
What have you put in the "project" subdirectory? Can you paste the output of "ls -la" here?

**Comment by iXieYi** [comment]
> What have you put in the "project" subdirectory? Can you paste the output of "ls -la" here?

![image](https://user-images.githubusercontent.com/21982108/112402350-5a2c9e00-8d47-11eb-9061-f492612e6eaa.png)

**Comment by iXieYi** [comment]
it is ok，but I  do nothing😝
![image](https://user-images.githubusercontent.com/21982108/112403335-2a7e9580-8d49-11eb-885b-7948d97ec36c.png)
