### ISSUE TITLE
Configuring Application Root Url

### ISSUE THREAD

**Issue by scchengaiah** [mendix/docker-mendix-buildpack#120]
Can someone please provide information on how to update application root url.

I am trying to fetch via Core runtime API that returns the value as https://example.docker.com

It seems to be a default value embedded inside the image configuration.

**Comment by zlogic** [comment]
If you need to set the [ApplicationRootUrl](https://docs.mendix.com/refguide/custom-settings#general) custom runtime setting, you can [specify](https://github.com/mendix/docker-mendix-buildpack#startup) the value through the `MXRUNTIME_ApplicationRootUrl` environment variable:

```
docker run ... -e MXRUNTIME_ApplicationRootUrl='http://domain-name-to-use.example.com'
```

**Comment by scchengaiah** [comment]
Thank you for the information @zlogic
