### ISSUE TITLE
Docker build failed (unsupported OS)

### ISSUE THREAD

**Issue by SanderTervoert** [mendix/docker-mendix-buildpack#166]
Hello, 
We are trying to upgrade to the V5 buildpack. I build the app and builder rootfs. 
I got the following error during the docker build command (step 21/40): 

`Traceback (most recent call last):
  File "./compilation.py", line 63, in <module>
    compilation_globals = call_buildpack_compilation()
  File "./compilation.py", line 34, in call_buildpack_compilation
    return runpy.run_module("buildpack.stage", run_name="__main__")
  File "/usr/lib64/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/mendix/buildpack/buildpack/stage.py", line 184, in <module>
    JAVA_VERSION,
  File "/opt/mendix/buildpack/buildpack/core/mxbuild.py", line 26, in build_from_source
    runtime_version, buildpack_path, cache_path
  File "/opt/mendix/buildpack/buildpack/core/mono.py", line 66, in ensure_and_get_mono
    dependency_name = _compose_mono_dependency_name(major_version)
  File "/opt/mendix/buildpack/buildpack/core/mono.py", line 51, in _compose_mono_dependency_name
    "Only Ubuntu is supported at present, "
Exception: Only Ubuntu is supported at present, requested distribution: rhel`

Quite interesting, since the docker buildpack is migrated from Ubuntu to Rhel.

CF-buildpack-version: 4.30.19
Docker buildpack version: 5.0.1
VM: ubuntu-latest ([microsoft hosted agent, ubuntu 22.04](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml))

Any suggestions? 
Thanks! 
Kind regards, 
Sander

**Comment by Christophe-Vico** [comment]
Same here.
CF-buildpack-version: 4.30.19 will fail to build.
And indeed, the file buildpack/core/mono.py does contain a hard check of the type of distri in the function `_compose_mono_dependency_name`

**Comment by zlogic** [comment]
@SanderTervoert @Christophe-Vico Could you please share details how you build the app (detailed steps to reproduce the issue)?
The Docker Buildpack already includes [measures to bypass this check](https://github.com/mendix/docker-mendix-buildpack/blob/08540aa81a723e95b935fd8f4f8d680d2da19ef1/rootfs-builder.dockerfile#L25) and works without issues with the default version of CF Buildpack.

**Comment by SanderTervoert** [comment]
If I check in the Docker build command, it says it is done: 
`Step 8/9 : RUN rm /etc/*-release && echo 'Ubuntu release 18.04 (Bionic)' > /etc/debian-release
 ---> Running in 9e99da215242
`

The build proces: 
The docker build command: 
`docker build -t $teamname:$buildId-app -f rootfs-app.dockerfile .`
`docker build -t $teamname:$buildId-builder -f rootfs-builder.dockerfile .`

We replace some values in the dockerfile so we can use our own tagged images: 
`sed -i -e '/ARG ROOTFS_IMAGE=/ s~=.*~='"$teamname:$buildId-app"'~' Dockerfile `
`sed -i -e '/ARG BUILDER_ROOTFS_IMAGE=/ s~=.*~='"$teamname:$buildId-builder"'~' Dockerfile `

For building the app, we use the following command: 
`        docker build . \ `
 `         --build-arg BUILD_PATH=mxsource \ `
 `         --tag $appname:$buildid \ `
 `         | tee $(Build.SourcesDirectory)/build-output.txt
`

**Comment by Christophe-Vico** [comment]
same process for me.

I build the :app & :builder images from the new dockerfile.
I updated the required ARG consequently.

checking the builder image:

`$ docker run -ti <my_registry>/rootfs:builder 
[root@b15a388e7acc /]# cat /etc/debian-release
Ubuntu release 18.04 (Bionic)`

So the fix has been applied in the builder image

**Comment by Christophe-Vico** [comment]
I just tried to inject the command before compiling, still failing:`

`INFO[0017] RUN rm /etc/*-release && echo 'Ubuntu release 18.04 (Bionic)' > /etc/debian-release 
INFO[0017] cmd: /bin/sh                                 
INFO[0017] args: [-c rm /etc/*-release && echo 'Ubuntu release 18.04 (Bionic)' > /etc/debian-release] 
INFO[0017] Running: [/bin/sh -c rm /etc/*-release && echo 'Ubuntu release 18.04 (Bionic)' > /etc/debian-release] 
INFO[0017] RUN cat /etc/debian-release                  
INFO[0017] cmd: /bin/sh                                 
INFO[0017] args: [-c cat /etc/debian-release]           
INFO[0017] Running: [/bin/sh -c cat /etc/debian-release] 
Ubuntu release 18.04 (Bionic)
`

**Comment by zlogic** [comment]
Hi @Christophe-Vico, @SanderTervoert, I've been able to reproduce the issues - at the moment, Docker Buildpack is only validated with CF Buildpack v4.30.17, doesn't yet support changes from CF Buildpack v4.30.19.

To keep builds working, the `master` branch will temporarily be reverted to the previous version of Docker Buildpack that still uses Ubuntu.

**Comment by SanderTervoert** [comment]
Thanks, that was indeed the issue. The following line in the readme got me:
`For stable pipelines, it's recommended to use a fixed version from v4.30.14 and later. CloudFoundry buildpack versions below v4.30.14 are not supported.`
It states that newer versions will work, but thats not the case. I switched to v4.30.14 and now it's all good. Thanks!
