### ISSUE TITLE
Exception: Only Ubuntu is supported at present, requested distribution: rhel

### ISSUE THREAD

**Issue by elouafi** [mendix/docker-mendix-buildpack#171]
Hello,
I'm trying to build a docker image using Docker Mendix Buildpack latest version using the following command but I got an exception.
`docker build -t mendix/test-project:latest --build-arg BUILD_PATH=project/ --build-arg CF_BUILDPACK=v4.30.19 -f Dockerfile .`
Error: 
` ---> Running in 767b68182aae
INFO: Mendix project compilation phase...
INFO: Preflight check on Mendix version [9.24.2.6130] and stack [None]...
INFO: Preflight check completed
INFO: Building from source...
INFO: Selecting Mono Runtime: 5
[91m/opt/mendix/buildpack/buildpack/infrastructure/database.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.primitives import serialization
[0m[91mTraceback (most recent call last):
  File "./compilation.py", line 63, in <module>
    compilation_globals = call_buildpack_compilation()
  File "./compilation.py", line 34, in call_buildpack_compilation
    return runpy.run_module("buildpack.stage", run_name="__main__")
  File "/usr/lib64/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/mendix/buildpack/buildpack/stage.py", line 184, in <module>
    JAVA_VERSION,
  File "/opt/mendix/buildpack/buildpack/core/mxbuild.py", line 26, in build_from_source
    runtime_version, buildpack_path, cache_path
  File "/opt/mendix/buildpack/buildpack/core/mono.py", line 66, in ensure_and_get_mono
    dependency_name = _compose_mono_dependency_name(major_version)
  File "/opt/mendix/buildpack/buildpack/core/mono.py", line 51, in _compose_mono_dependency_name
    "Only Ubuntu is supported at present, "
Exception: Only Ubuntu is supported at present, requested distribution: rhel`

Thanks for your support  !

**Comment by zlogic** [comment]
Hi @elouafi, CF Buildpack v4.30.19 is not yet supported, can you please switch to v4.39.17?

If you would like to use a later CF Buildpack version, at the moment you would need to use the https://github.com/mendix/docker-mendix-buildpack/pull/169 branch.
