### ISSUE TITLE
Kill master branch?

### ISSUE THREAD

**Issue by guenhter** [mendix/docker-mendix-buildpack#179]
Hi,

it is confusing everytime when going to the github page and then realizing that the `master` branch is actually not really the master but just some legacy thing.

Couldn't this be killed and `latest` be made the default branch?

**Comment by zlogic** [comment]
The `master` branch exists to keep existing pipelines working.
Many pipelines were set up using the default branch and are incompatible with the latest version, so the `master` (or any default branch) needs to remain compatible with those pipelines.

It's better to use specific fixed tags or revisions to ensure that pipelines are stable, and manually update the Docker Buildpack version/tag.

**Comment by guenhter** [comment]
Thx
