### ISSUE TITLE
Mendix 10.3.0 Docker build failed 

### ISSUE THREAD

**Issue by elouafi** [mendix/docker-mendix-buildpack#185]
Hello,
We setup our pipeline on Jenkins to build and release Mendix 10.3.0 project. 
We got the following error:  ERROR: The project cannot be deployed, because it contains errors.
ERROR at (unknown location): The theme could not be compiled:

App and Builder images are built using this repo https://github.com/mendix/docker-mendix-buildpack.git tag : v5.0.2

Thanks for your help !

**Comment by zlogic** [comment]
Hello @elouafi, Docker Buildpack was tested and confirmed to work with Mendix 10.3. From the error message you've shared, it appears that your project cannot be compiled because it contains errors.

Can you try building the project MDA from Studio Pro (instead of Docker Buildpack), or opening a support case?

**Comment by elouafi** [comment]
The project seems to be built successfully using Studio Pro local run or MDA too.
I'm trying to test a new project created from Web Blank template for Mx 10.3.0 and check if the pipeline is working

Thanks for your response.

**Comment by mruiserr** [comment]
Hi @elouafi are you running the project in a network folder? If so are you able to move the project to a local folder?

**Comment by elouafi** [comment]
@mruiserr  I'm running the pipeline using Jenkins inside a VM. I replicated same steps locally ans still having same error.
@zlogic : I tested using a new project and it's working 💯  . Is there any way to get verbose log about the build steps (compilation ...)?

**Comment by elouafi** [comment]
It's Ok now.
The issue was about custom-variables.scss import from themsource folder. We used camel case while the directory was in lower case. Windows do treat it as same folder while build on docker consider that as different folder.

Thanks all for your help !
