### ISSUE TITLE
Cannot open assembly '/opt/mendix/build/.local/mxbuild/modeler/mxbuild.exe': No such file or directory.

### ISSUE THREAD

**Issue by anahitdshr** [mendix/docker-mendix-buildpack#194]
Hello,

I'm encountering an error when building the image after upgrading the project to Mendix v10.6.8. It worked perfectly fine with Mendix v9.24.2.

The error log I'm receiving is: 
`> [builder 7/7] RUN mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache /tmp/cf-deps 0 &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chmod -R g=u /opt/mendix /var/mendix:
1.103 INFO: Mendix project compilation phase...
2.120 INFO: Preflight check on Mendix version [10.6.8.33522] and stack [None]...
2.120 INFO: Mendix [10.6] is not maintained. Please use a medium- or long-term supported Mendix version to easily receive fixes (https://docs.mendix.com/releasenotes/studio-pro/lts-mts).
2.120 INFO: Preflight check completed
2.121 INFO: Building from source...
2.122 INFO: Selecting Mono Runtime: 5
144.0 Cannot open assembly '/opt/mendix/build/.local/mxbuild/modeler/mxbuild.exe': No such file or directory.
144.0 ERROR: Could not read MxBuild error file
144.0 Traceback (most recent call last):
144.0   File "/opt/mendix/buildpack/buildpack/core/mxbuild.py", line 70, in build_from_source
144.0     subprocess.check_call(args, env=mono_env)
144.0   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
144.0     raise CalledProcessError(retcode, cmd)
144.0 subprocess.CalledProcessError: Command '['/tmp/opt/mono-5.20.1.27/bin/mono', '--config', '/tmp/opt/mono-5.20.1.27/etc/mono/config', '/opt/mendix/build/.local/mxbuild/modeler/mxbuild.exe', '--target=package', '--output=/tmp/model.mda', '--java-home=/opt/mendix/build/.local/usr/lib/jvm/Adoptium-jdk-11.0.16-Adoptium-x64', '--java-exe-path=/opt/mendix/build/.local/usr/lib/jvm/Adoptium-jdk-11.0.16-Adoptium-x64/bin/java', '--write-errors=/tmp/builderrors.json', '/opt/mendix/build/DatascaleHR.mpr']' returned non-zero exit status 2.
144.0
144.0 During handling of the above exception, another exception occurred:
144.0
144.0 Traceback (most recent call last):
144.0   File "/opt/mendix/buildpack/buildpack/core/mxbuild.py", line 117, in _log_buildstatus_errors
144.0     with codecs.open(error_file, "r", encoding="utf-8-sig") as errorfile:
144.0   File "/usr/lib/python3.6/codecs.py", line 897, in open
144.0     file = builtins.open(filename, mode, buffering)
144.0 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/builderrors.json'
144.0 ERROR: MxBuild returned errors: {"problems": [{"severity": "Error", "message": "Failed to build the model,please check application logs for details.", "locations": []}]}
144.0 ERROR: Command '['/tmp/opt/mono-5.20.1.27/bin/mono', '--config', '/tmp/opt/mono-5.20.1.27/etc/mono/config', '/opt/mendix/build/.local/mxbuild/modeler/mxbuild.exe', '--target=package', '--output=/tmp/model.mda', '--java-home=/opt/mendix/build/.local/usr/lib/jvm/Adoptium-jdk-11.0.16-Adoptium-x64', '--java-exe-path=/opt/mendix/build/.local/usr/lib/jvm/Adoptium-jdk-11.0.16-Adoptium-x64/bin/java', '--write-errors=/tmp/builderrors.json', '/opt/mendix/build/DatascaleHR.mpr']' returned non-zero exit status 2.
144.0 /opt/mendix/buildpack/buildpack/infrastructure/database.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
144.0   from cryptography.hazmat.primitives import serialization
144.2 /opt/mendix/buildpack/buildpack/infrastructure/database.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
144.2   from cryptography.hazmat.primitives import serialization
144.2 Traceback (most recent call last):
144.2   File "./compilation", line 67, in <module>
144.2     exit_code = call_buildpack_compilation()
144.2   File "./compilation", line 40, in call_buildpack_compilation
144.2     return subprocess.check_call(["/opt/mendix/buildpack/buildpack/stage.py", BUILD_PATH, CACHE_PATH, DEPS_DIR, DEPS_IDX])
144.2   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
144.2     raise CalledProcessError(retcode, cmd)
144.2 subprocess.CalledProcessError: Command '['/opt/mendix/buildpack/buildpack/stage.py', '/opt/mendix/build', '/tmp/buildcache', '/tmp/cf-deps', '0']' returned non-zero exit status 1.
------
Dockerfile:73
--------------------
  72 |     # 8. Update permissions of /opt/mendix so that the app can run as a non-root user
  73 | >>> RUN mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&\
  74 | >>>     chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py &&\
  75 | >>>     cd /opt/mendix/buildpack &&\
  76 | >>>     ./compilation /opt/mendix/build /tmp/buildcache /tmp/cf-deps 0 &&\
  77 | >>>     rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&\
  78 | >>>     ln -s /opt/mendix/.java /opt/mendix/build &&\
  79 | >>>     # chown -R ${USER_UID}:0 /opt/mendix /var/mendix &&\
  80 | >>>     chmod -R g=u /opt/mendix /var/mendix
  81 |
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir -p /tmp/buildcache /tmp/cf-deps /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git /opt/mendix/buildpack/buildpack/stage.py &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache /tmp/cf-deps 0 &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chmod -R g=u /opt/mendix /var/mendix" did not complete successfully: exit code: 1

Is there any solution to this.

Best regards,
Anahit Pahlevanyan

**Comment by anahitdshr** [comment]
Anyone having similar issue just update CF buildpack version

**Comment by anahitdshr** [comment]
Anyone having similar issue just update CF buildpack version

**Comment by josevaldojnr** [comment]
Thanks, dumb me was trying to understand what was going on, was working on an older release and didn't even realized I've cloned the wrong branch
