### ISSUE TITLE
Server ID

### ISSUE THREAD

**Issue by drewtwitchell** [mendix/docker-mendix-buildpack#28]
How do I find the server ID to give to Mendix support? It doesn't appear to install the m2ee tools for me to run that command to find the ID

**Comment by piranha79** [comment]
Same question as @drewtwitchell over here. Is anyone reading?

**Comment by MXClyde** [comment]
If you want to request a Docker license from Mendix Support a server ID is not needed. Just submit a ticket requesting the app you want to have a Docker license for (make sure to specify you want a Docker license).  When you are eligible for a Docker licensem they will start the procedure to provision a Docker license for you.
