### ISSUE TITLE
Pull access denied for mendix/mendix-buildpack

### ISSUE THREAD

**Issue by vincevannoort** [mendix/docker-mendix-buildpack#35]
When running ```make run-container```,  i get the following error message:

```
docker-compose -f tests/docker-compose-postgres.yml up
Pulling mendixapp (mendix/mendix-buildpack:v1.4)...
ERROR: pull access denied for mendix/mendix-buildpack, repository does not exist or may require 'docker login'
make: *** [run-container] Error 1
```

Any idea why?

**Comment by vincevannoort** [comment]
I've figured it out, the file https://github.com/mendix/docker-mendix-buildpack/blob/master/Makefile makes a image called ```mendix/mendix-buildpack:v1.3```, while the compose file https://github.com/mendix/docker-mendix-buildpack/blob/master/tests/docker-compose-postgres.yml references a different image called ```mendix/mendix-buildpack:v1.4```.

Would you like me to make a pull request?

**Comment by dudk** [comment]
Issue was fixed
