### ISSUE TITLE
Access denied to  "/buildpack/compilation"

### ISSUE THREAD

**Issue by vicam001** [mendix/docker-mendix-buildpack#46]
When executing this statement of the Dockerfile

# Compile the application source code and remove temp files
WORKDIR /buildpack
RUN  /buildpack && "/buildpack/compilation" /build /cache && \
    rm -fr /cache /tmp/javasdk /tmp/opt

The following error appears:

Step 11/20 : RUN "/buildpack/compilation" /build /cache &&   rm -fr /cache /tmp/javasdk /tmp/opt
 ---> Running in ac04f5b273cd
/bin/sh: 1: /buildpack/compilation: **Permission denied**
The command '/bin/sh -c "/buildpack/compilation" /build /cache &&   rm -fr /cache /tmp/javasdk /tmp/opt' returned a non-zero code: 126
ERROR: Job failed: exit code 126

**Comment by sheperdsonbrown** [comment]
RUN chmod +x /buildpack/compilation

**Comment by cstevandy** [comment]
The https://github.com/mendix/docker-mendix-buildpack/pull/58 added the chmod so I will close this issue
