### ISSUE TITLE
Run container as non root

### ISSUE THREAD

**Issue by bramvdklinkenberg** [mendix/docker-mendix-buildpack#65]
Hi, I would like to know if there is a way to run the container as non root user?
We will enable pod security and set policies so containers cannot run as root or in priviliged mode. This will have impact on our mendix containers, which are running as root.

**Comment by dudk** [comment]
Hello @bramvdklinkenberg. We have a PR in progress, you can check #64 for more information. Implementation is finished, it just goes through the final review stages and will be published to `master` as v2.0.0 very soon.

**Comment by bramvdklinkenberg** [comment]
Nice!
