### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git'

### ISSUE THREAD

**Issue by nezoic** [mendix/docker-mendix-buildpack#85]
I'm attempting to build this in Azure Devops on an Ubuntu 18.04 host. I keep seeing this error but I'm not sure what it means other than 'git' is missing? Does this mean that git needs to be installed or this folder created?

`
Executing step 'Synchronize with file system'

Synchronizing with file system...
Executing step 'Initialize'
Preparing deployment...
Executing step 'Check prerequisites'
Checking for errors...
Executing step 'Clean deployment directory'
Cleaning deployment directory...
Cleaning web deployment directory...
Executing step 'Prepare deployment'
Writing files...
Executing step 'Build deployment structure'
Compiling Java...
Generating integration files...
Exporting a theme...
Exporting pages...
Optimizing...
Exporting custom widgets...
Bundling custom widgets...
Compiling JavaScript actions...
Compressing web resources...
Executing step 'Save model to deployment directory'
Saving model to deployment directory...
Executing step 'Create deployment package'
Creating deployment package...
Executing step 'Finalize deployment package'
BUILD SUCCEEDED
WARNING: MENDIX BUILDPACK: Unable to determine exact version in use. This is nothing to worry about
Traceback (most recent call last):
File "/opt/mendix/buildpack/bin/../bin/compile.py", line 65, in get_current_git_commit
["git", "rev-parse", "HEAD"], cwd=BUILDPACK_DIR
File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
File "/usr/lib/python3.4/subprocess.py", line 859, in init
restore_signals, start_new_session)
File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
INFO: buildpack compile completed

**Comment by zlogic** [comment]
This issue is fixed in the https://github.com/mendix/docker-mendix-buildpack/releases/tag/v2.3.2 release.
