### ISSUE TITLE
ModuleNotFoundError: No module named 'buildpackutil'

### ISSUE THREAD

**Issue by eist** [mendix/docker-mendix-buildpack#90]
Hi,

we are seeing build issues using docker-mendix-buildpack master after cf-mendix-buildpack has been upgraded to v4.5.0 (Mendix Cloud Foundry Buildpack v4.5.0).

·[91mTraceback (most recent call last):
--
964 | File "./compilation", line 9, in <module>
965 | import buildpackutil
966 | ModuleNotFoundError: No module named 'buildpackutil'
967 | ·[0mThe command '/bin/sh -c mkdir -p /tmp/buildcache /var/mendix/build /var/mendix/build/.local &&    chmod +rx /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    cd /opt/mendix/buildpack &&    ./compilation /opt/mendix/build /tmp/buildcache &&    rm -fr /tmp/buildcache /tmp/javasdk /tmp/opt /tmp/downloads /opt/mendix/buildpack/compilation /opt/mendix/buildpack/git &&    ln -s /opt/mendix/.java /opt/mendix/build &&    chgrp -R 0 /opt/mendix /var/mendix &&    chmod -R g=u /opt/mendix /var/mendix' returned a non-zero code: 1

**Comment by eist** [comment]
there might be a change needed for all the files using 'import buildpackutil' under docker-mendix-buildpack/scripts/ (like compilation or cleanupjdk):

-- `import buildpackutil`
++ `from buildpack import util`

**Comment by eist** [comment]
seems like https://github.com/mendix/docker-mendix-buildpack/pull/88 will be addressing this.

**Comment by raymonvt** [comment]
same problem here, it worked fine last week.

**Comment by MXClyde** [comment]
As described [here](https://github.com/mendix/docker-mendix-buildpack#usage), this can be worked around by pinning to a specific earlier CF buildpack version using CF_BUILDPACK env var.

**Comment by zlogic** [comment]
As mentioned by @MXClyde, setting the `CF_BUILDPACK` build argument to `v4.4.2` will switch to a CF Buildpack which is known to be compatible with the current Docker Buildpack:
```
docker build \
--build-arg CF_BUILDPACK=v4.4.2 \
...
```

**Comment by eist** [comment]
it's working now again. thanks for resolving this so quick
